### ISSUE TITLE
Cache poetry dependencies in workflows

### ISSUE THREAD

**Issue by engnadeau** [engnadeau/pybotics#794]
## User Story

Dev wants to cache poetry dependencies for faster workflow runs

## Potential Solutions

- Use the poetry cache option in `actions/setup-python@v4`:

```yml
- uses: actions/setup-python@v4
  with:
    python-version: "3.x"
    cache: "poetry"
```

## Additional Context

- Currently failing due to poetry not being available early in the workflow: https://github.com/engnadeau/pybotics/runs/7921609651?check_suite_focus=true
- Apparently a new release is incoming: https://github.com/actions/setup-python/issues/369#issuecomment-1214675418
