### ISSUE TITLE
Dev wants to use poetry dependency groups to better separate venvs

### ISSUE THREAD

**Issue by engnadeau** [engnadeau/pybotics#798]
## User Story

- Dev wants to use poetry dependency groups to better separate venvs

## Potential Solutions

e.g:

```toml
[tool.poetry.dependencies]
python = "^3.7"
attrs = ">=19.0"
numpy = "^1.9"
scipy = "^1"

[tool.poetry.group.dev.dependencies]
black = ">=22.1"
coverage = ">=6"
flake8 = ">=4"
flake8-bugbear = ">=22"
hypothesis = ">=6"
isort = ">=5.5"
mccabe = ">=0.7"
mypy = ">=0.960"
pep8-naming = ">=0.12"
pydocstyle = ">=6"
pytest = ">=7"
pytest-cov = ">=3"
pytest-randomly = ">=3.8"
pytest-runner = ">=5.3"
rope = ">=1"
vulture = ">=2.0"

[tool.poetry.group.notebooks]
optional = true

[tool.poetry.group.notebooks.dependencies]
matplotlib = ">=3.4"
notebook = ">=6.4"
pandas = ">=1.1.0"
scikit-learn = ">=1"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = ">=4"
sphinx-autobuild = "*"
sphinx-rtd-theme = ">=1"
sphinxcontrib-apidoc = ">=0.3.0"

```

## Additional Context

- https://python-poetry.org/docs/master/managing-dependencies/#dependency-groups
  - Need to wait till next poetry release
- https://github.com/graphql-python/graphql-core/issues/177
- https://github.com/sphinx-doc/sphinx/issues/10241
